package com.judy;

import java.io.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class FindStrInDir
{
    //static String BUSINESS = "ch";

    // test : "E:\\test";
    //"C:\\workspace\\hobis\\hnid\\htm\\"+BUSINESS;    //검색할 디렉토리
    //"C:\\workspace\\hobis\\hnid\\src\\"+BUSINESS

    //static String TARGET_DIR = "C:\\workspace\\hobis\\hnid\\src\\"+BUSINESS;    //검색할 디렉토리
    static String FIND_WORD = "ServiceName";         //검색할단어를,로 구분해서 나열

    static String TARGET_WORD = "UPDATE";
    static String SAVE_DIR = "E:\\result\\";

    public static void main( String[] args ) throws Exception
    {
        String biz;

        String[] BizList = getBizList();

        List<String> TotalrsltList = new ArrayList<>();

        for(int i =0; i < BizList.length; i++) {

            biz = BizList[i];
            List<String> rsltList =  createUpdateSqlList(biz);
            TotalrsltList.addAll(rsltList);
        }

        createOutputFile(TotalrsltList);
    }

    private static List<String> createUpdateSqlList(String biz) throws IOException {

        File file = new File("C:\\workspace\\hobis\\hnid\\src\\"+biz);
        File[] Files = file.listFiles();

        List<String> rsltList = new ArrayList<>(); //처음 dir 돌려서 관련 있는애들 나오는거 저장
        Map<String, String> rsltMap = new HashMap<>(); //key에는 화면명, value에는 소스명 저장

        //읽어들일 파일 input stream 선언
        BufferedReader br;
        String[] words = FIND_WORD.split(",");

        //해당하는 문자들 추출
        for(int i = 0; i < Files.length; i++)
        {
            //파일이 아닌 경우 continue
            if (!Files[i].isFile())
            {
                continue;
            }

            //input stream object 생성
            br = new BufferedReader(new FileReader(Files[i]));
            String line = "";

            boolean check  = false; // 처음찾는경우  false  이전라인에 EXEC  SQL 있었으면 false
            boolean check2 = false; // update 단어
            String  checkVal = "";
            String tableName = "";

            //각 파일의 한 라인씩 읽어들인다.
            while ((line = br.readLine()) != null)
            {
                //line 대문자 변경
                line = line.toUpperCase();

                // 만약 check2가 true 이면 바로 테이블명 점검 !
                if(check2){

                    System.out.println("--- check2 --- ");
                    //있으면 table 찾기
                    tableName =  solution(line);

                    if(tableName != null){
                        //System.out.println("line2:" + line);
                        // System.out.println("tableName2:" + tableName);

                        if(checkVal.equals("U")){

                            rsltList.add(Files[i].getAbsolutePath() + "=" + tableName+"=U");

                        }else if(checkVal.equals("I")){

                            rsltList.add(Files[i].getAbsolutePath() + "=" + tableName+"=I");
                        }
                    }

                    check = false;
                    check2 = false;
                    checkVal = "";
                    // tableName 이 null이든 아니든 ,  다음 udpate 구문 찾기로 변경

                }

                if(check){ // check 가 true 이면 이전에 exec sql 이 있던경우

                    if(line.contains("UPDATE")){ //해당라인에 update 가 있는지 확인

                        // System.out.println("line1:" + line);
                        //있으면 table 찾기
                        tableName =  solution(line);

                        if(tableName != null){
                            // System.out.println("tableName1:" + tableName);
                            rsltList.add(Files[i].getAbsolutePath() + "=" + tableName+"=U");

                        }else{
                            // update 단어 다음에 null 이거나 주석인경우 , 테이블 형태가 아닌경우
                            check2 = true; // update 단어
                            checkVal = "U";

                        }
                    }else if(line.contains("INSERT")){

                        // System.out.println("line1:" + line);
                        //있으면 table 찾기
                        tableName =  solution(line);

                        if(tableName != null){
                            // System.out.println("tableName1:" + tableName);
                            rsltList.add(Files[i].getAbsolutePath() + "=" + tableName+"=I");

                        }else{
                            // update 단어 다음에 null 이거나 주석인경우 , 테이블 형태가 아닌경우
                            check2 = true; // update 단어
                            checkVal = "I";

                        }
                    }
                    check = false;

                }else{

                    if(line.contains("EXEC")){

                        if(line.contains("SQL")){

                            if(line.contains("END")){
                                //skip!
                                check = false;
                            }else{

                                check = true;
                                if(line.contains("UPDATE")){
                                    // System.out.println("line2:" + line);
                                    //있으면 table 찾기
                                    tableName =  solution(line);

                                    if(tableName != null){
//                                        System.out.println("line2 _ :" + line);
//                                        System.out.println("tableName2:" + tableName);

                                        rsltList.add(Files[i].getAbsolutePath() + "=" + tableName+"=U");
                                        check = false;

                                    }else{

                                        // udpate 다음문자가 null 이거나 ,주석, 테이블형태가 아니면
                                        check2 = true; // update 단어
                                        checkVal = "U";

                                    }
                                }else  if(line.contains("INSERT")){

                                    //있으면 table 찾기
                                    tableName =  solution(line);

                                    if(tableName != null){
//                                        System.out.println("line2 _ :" + line);
//                                        System.out.println("tableName2:" + tableName);

                                        rsltList.add(Files[i].getAbsolutePath() + "=" + tableName+"=I");
                                        check = false;

                                    }else{
                                        //System.out.println("line2 _ check2:" + line);
                                        // insert 다음문자가  테이블형태가 아니면
                                        check2 = true; //
                                        checkVal = "I";

                                    }
                                }
                            }
                        }
                    }
                }
            }
            //input stream close.
            br.close();
        }


        System.out.println("rsltList1 size:" + rsltList.size());

        //rsltList 중복제거
        rsltList = rsltList.stream().distinct().collect(Collectors.toList());

        System.out.println("rsltList2 size:" + rsltList.size());

        return rsltList;
    }

    public static void createOutputFile(List<String> rsltList) throws IOException {

        //저장할 파일 output stream 생성
        //PrintWriter writer = new PrintWriter(new FileWriter(SAVE_DIR + biz+".txt"));
        PrintWriter writer = new PrintWriter(new FileWriter(SAVE_DIR + "hobisSql"+".txt"));

        for(String rslt : rsltList)
        {
            // System.out.println("rslt:" + rslt);
            String rsltTmp1 = ""; //서비스명 저장
            String rsltTmp2 = ""; //table명 저장
            String rsltTmp3 = ""; //update,insert 저장

            String[] words2 = rslt.split("=");
            rsltTmp1 = words2[0];
            rsltTmp2 = words2[1];
            rsltTmp3 = words2[2];

            System.out.println(rsltTmp3 + ", " + rsltTmp2 + ", " + rsltTmp1);

            writer.write(rsltTmp2 + "," + rsltTmp1 +","+ rsltTmp3 +"\n");
//            System.out.println("rsltTmp2 = " + rsltTmp2);
        }
//        output stream close.
        writer.close();

    }


    //UPDATE 다음 문자열 얻기
    public static String solution(String input) {
        System.out.println("input : " + input);
      //  String newStr = input.replaceAll("\\s+", " ");     // 연속된 공백 -> 하나의 공백으로
      //  String[] words = newStr.split(" ");                          //공백으로 구분


//        int max = 0;
//        int index = 0;
//        for (int i = 0; i < words.length; i++) {
//            if (words[i].equals("UPDATE")) { // 단어가 더 길면 max가 바뀜
//               // 다음 문자열 얻기
//                index = i++;
//            }
//        }
//
//        index = index+1;
//
//        if(words.length > index){
//
//            if(words[index] != null){
//
//                // 다음단어가 주석이면 null
//                if(words[index].startsWith("/*")){
//                    return null;
//                }
//
//                if(words[index].contains("_")){
//                    System.out.println("words[index] : " + words[index]);
//                    return words[index];
//                }
//            }
//        }

        String newStr = input.replaceAll("\\s+", " ");     // 연속된 공백 -> 하나의 공백으로
        String[] words = newStr.split(" ");


        String[] tableList = getTableList();

        for (int i = 0; i < words.length; i++) { // 해당 대상 라인의 단어들

            for(int j =0; j < tableList.length; j++) {

                if( words[i].equals(tableList[j])){ // 실제 존재하는 테이블 리스트와 동일한 경우만 return
                    return tableList[j];
                }
            }
        }


//        for(int i =0; i < tableList.length; i++) {
//
//            if(input.indexOf(tableList[i]) != -1)
//            {
//                return tableList[i];
//            }
//        }

        return  null;
    }

    private static String[] getTableList() {

        String[] tableList = {
                "ACOM_NOTIF_SMS_BLAST",
                "ADST_LNB_COLL_WAIVE",
                "BCK_ADT_OJK_2021_CIX_V1",
                "BCK_ADT_OJK_2021_CIX_V2",
                "BCK_ADT_OJK_2021_CIX_V3",
                "SISMONTAVAR_INQ",
                "ACOM_FXTRX_BASE_BACKUP",
                "AEBK_BIFS_STTL_HIS",
                "AEBK_BIFS_TRX_HIS",
                "ACOM_POA_HIS",
                "ACOM_COMH_REFALLOW_IFRS_MIRROR",
                "AEBK_CSH_CASE_DETAIL",
                "MIG_TABLE_LIST",
                "ACOM_CIX_KYCHIS",
                "MRTP_RE62_SLA01",
                "MRTP_RE62_SLD01",
                "MRTP_RE62_SLD02",
                "MRTP_RE62_SLM01",
                "MRTP_RE62_SLP01",
                "ACOM_COM_EXRTINFO",
                "ADST_DPB_BAT",
                "ACOM_CIX_EXT1",
                "AEBK_BOH_SUSP",
                "ADST_LNB_BRPT",
                "ADST_LNB_BRPT_HIS",
                "ADST_LNB_CONT_HIS",
                "AEBK_BXH_HIS",
                "AEBK_BOH_RESP",
                "AEBK_BFH_TRAN",
                "AEBK_BFH_PRXY",
                "AEBK_BFH_MAP",
                "AEBK_BOH_SESS",
                "AEBK_BFH_MAP_OUT",
                "AEBK_BFH_PRXY_HIS",
                "AFTC_FTH_APPLY",
                "AFTC_FTH_BASE",
                "AFTC_FTH_CANCEL",
                "AFTC_FTH_REPAY",
                "AFTC_FTH_BUYBACK",
                "AFTC_FTH_BUYBACK_REPORT",
                "AFTC_FTH_EARLY_PAIDOFF",
                "ADST_LNB_APC_BASE",
                "AFBK_FKH_HLI_ERR_LOG",
                "ACOM_OVERDUE_BASE_MIRROR",
                "ACOM_OVERDUE_DTLS_MIRROR",
                "ACOM_OVERDUE_PTCL_MIRROR",
                "MRTP_RE62_LN001",
                "ACOM_COM_DTBANK_BACKUP",
                "ACOM_TRSC_ASO_REL",
                "AFEX_IPH_DOC",
                "AFEX_IPH_DOCHIS",
                "AEBK_EOH_SMS_BF",
                "AEBK_EOH_SMS_AF",
                "ACOM_EPB_REPORT",
                "MRTP_RE62_CM013",
                "AEBK_BFH_RECON_BI",
                "AEBK_BFH_RECON_HANA",
                "MRTP_RE62_SLF03",
                "ACOM_COMH_FRECOG",
                "MRTP_RE62_SLF04",
                "MRTP_RE62_SLF05",
                "AEBK_BFH_RECON_HIS",
                "AEBK_BFH_RECON_BASE",
                "ALOG_LB_APIGW",
                "AEBK_BOH_SUSPHIS",
                "ACOM_COMH_PPATK",
                "AFTC_FTH_BASE_HIS",
                "FBCD_CPF_PAY_ACCT",
                "AFTC_FTH_RECON",
                "ACOM_CIX_WARN",
                "FBCD_FUND_POI",
                "ACOM_POI_TRAN",
                "AEBK_ECH_BAT_VA_PTCL",
                "AEBK_ECH_BAT_VA_BASE",
                "TEMP_LISKA",
                "ACOM_COMH_REFALLOW_MIRROR",
                "ACOM_EDD_BASE_OLD",
                "ACOM_EDD_BASE",
                "DEPT_JSON_HEADER",
                "TEMP_TABLE_FDS",
                "AEBK_CSH_B24_AI02_BAK",
                "AEBK_CSH_IDEA_NPG_P_01",
                "AEBK_CSH_IDEA_NPG_P_03",
                "AEBK_CSH_IDEA_NPG_P_04",
                "AEBK_CSH_IDEA_VISA_03",
                "AEBK_CSH_IDEA_VISA_04D",
                "AEBK_CSH_IDEA_VISA_TNP_HBS",
                "AEBK_CSH_P_B_HOBIS_BAK",
                "ADST_OTHL_BASE",
                "ADST_OTHL_RECOV_HIS",
                "ADST_OTHL_RECOV",
                "ADST_OTHL_TARGET",
                "AACT_ACC_CLSBR",
                "AACT_ACC_CLSDAY",
                "AACT_ACC_CLSPGM",
                "AACT_ACR_BAL",
                "AACT_ACR_BASE",
                "AACT_ACR_TRAN",
                "AACT_ACT_CIFNO",
                "AACT_ACT_DATE",
                "AACT_ACT_DATE_TMP",
                "AACT_ACT_EVNT_BASE",
                "AACT_ACT_EVNT_PTCL",
                "AACT_ACT_JUKSU",
                "AACT_ACT_REFHIS",
                "AACT_ACT_REFNO",
                "AACT_OTB_BASE",
                "AACT_OTB_HIS",
                "AACT_OTB_MSE",
                "AACT_OTB_PJ",
                "AACT_OTB_PJ_DAILY",
                "AACT_OTK_BASE",
                "AACT_OTK_HIS",
                "AACT_TEL_ACT",
                "AACT_TEL_BAL",
                "AACT_TEL_BASE",
                "AACT_TEL_CASH",
                "AACT_TRX_BATCHACT",
                "AACT_TRX_SEQ",
                "ACOM_ATB_BASE",
                "ACOM_ATB_BATCH",
                "ACOM_ATB_HIS",
                "ACOM_ATB_SALARY",
                "ACOM_BIB_BASE",
                "ACOM_BIB_HIS",
                "ACOM_BIB_ITM",
                "ACOM_BIB_TOT",
                "ACOM_BIX_BASE",
                "ACOM_BOPU_BASE",
                "ACOM_BOPU_RPTDATA",
                "ACOM_BOP_BASE",
                "ACOM_BOP_HIS",
                "ACOM_BOP_RPT",
                "ACOM_BOP_RPTDATA",
                "ACOM_CIX_ACNO",
                "ACOM_CIX_BASE",
                "ACOM_CIX_BOD",
                "ACOM_CIX_FEX",
                "ACOM_CIX_ITM",
                "ACOM_CIX_LRPT",
                "ACOM_CIX_MEMO",
                "ACOM_CIX_SHLDR",
                "ACOM_COH_ABA",
                "ACOM_COH_BANK",
                "ACOM_COH_BASE",
                "ACOM_COH_INFO",
                "ACOM_COH_MEET",
                "ACOM_COH_MEETDES",
                "ACOM_COMH_AUTO",
                "ACOM_COMH_BATCHSTS",
                "ACOM_COMH_BDCOMM",
                "ACOM_COMH_BRGRANT",
                "ACOM_COMH_CERT",
                "ACOM_COMH_CERTHIS",
                "ACOM_COMH_CODE",
                "ACOM_COMH_CODEBR",
                "ACOM_COMH_COPY",
                "ACOM_COMH_CREDITCODE",
                "ACOM_COMH_CTRYCREDIT",
                "ACOM_COMH_CUST",
                "ACOM_COMH_CUSTCREDIT",
                "ACOM_COMH_CUSTDEPO",
                "ACOM_COMH_DAMBO",
                "ACOM_COMH_DEALER",
                "ACOM_COMH_DEALERHIS",
                "ACOM_COMH_DUP",
                "ACOM_COMH_FBCOMM",
                "ACOM_COMH_FEECOMM",
                "ACOM_COMH_FGCOMM",
                "ACOM_COMH_FXCOMM",
                "ACOM_COMH_GRANTTRANS",
                "ACOM_COMH_GROUP",
                "ACOM_COMH_GRPGRANT",
                "ACOM_COMH_JOBKIND",
                "ACOM_COMH_MANAGER",
                "ACOM_COMH_MARGIN",
                "ACOM_COMH_MENU",
                "ACOM_COMH_MMCOMM",
                "ACOM_COMH_MPS",
                "ACOM_COMH_MSG",
                "ACOM_COMH_MSGCNT",
                "ACOM_COMH_MSGHIS",
                "ACOM_COMH_MSGSAR",
                "ACOM_COMH_POBASE",
                "ACOM_COMH_REFALLUSE",
                "ACOM_COMH_REFCREDIT",
                "ACOM_COMH_SESSION",
                "ACOM_COMH_SESSPOOL",
                "ACOM_COMH_SQLSTT",
                "ACOM_COMH_STLBANK",
                "ACOM_COMH_SWCOMM",
                "ACOM_COMH_TAGDESC",
                "ACOM_COMH_TAGFMT",
                "ACOM_COMH_TAGLINE",
                "ACOM_COMH_TAGNO",
                "ACOM_COMH_TERMINFO",
                "ACOM_COMH_TODOLIST",
                "ACOM_COMH_TRMK",
                "ACOM_COMH_TYPE",
                "ACOM_COMH_USER",
                "ACOM_COMH_USERGRANT",
                "ACOM_COMH_USERHIS",
                "ACOM_COM_ACTCD",
                "ACOM_COM_ACTCDMAP",
                "ACOM_COM_BATSEQ",
                "ACOM_COM_CCY",
                "ACOM_COM_CD",
                "ACOM_COM_CDAPL",
                "ACOM_COM_CDSIL",
                "ACOM_COM_CERT",
                "ACOM_COM_CERTHIS",
                "ACOM_COM_CERTUSE",
                "ACOM_COM_CHREF",
                "ACOM_COM_CODE",
                "ACOM_COM_CTRY",
                "ACOM_COM_CUSTFEE",
                "ACOM_COM_DAYINF",
                "ACOM_COM_DTBANK",
                "ACOM_COM_ERR",
                "ACOM_COM_ESTIM",
                "ACOM_COM_EXRT",
                "ACOM_COM_FAVORITE",
                "ACOM_COM_FEECD",
                "ACOM_COM_FEERT",
                "ACOM_COM_FPBODY",
                "ACOM_COM_FPHEAD",
                "ACOM_COM_FTPAPL",
                "ACOM_COM_FTPSIL",
                "ACOM_COM_GIIL",
                "ACOM_COM_HOLI",
                "ACOM_COM_HQACTCD",
                "ACOM_COM_HSCODE",
                "ACOM_COM_IKIS",
                "ACOM_COM_INTRT",
                "ACOM_COM_NOTIFY",
                "ACOM_COM_PRGEXT",
                "ACOM_COM_PRGINFO",
                "ACOM_COM_PRGSHPE",
                "ACOM_COM_RCPT",
                "ACOM_COM_RELREF",
                "ACOM_COM_RELREF_HIS",
                "ACOM_COM_SLIP",
                "ACOM_COM_TRCOMM",
                "ACOM_COM_USERMAP",
                "ACOM_COM_VALID",
                "ACOM_COM_VALID_DTLS",
                "ACOM_COM_VOUCHER",
                "ACOM_COM_YRATE",
                "ACOM_CONT_BASE",
                "ACOM_CONT_INTHIS",
                "ACOM_CONT_INTINFO",
                "ACOM_DMH_ALLOC",
                "ACOM_DMH_ALLOCHIS",
                "ACOM_DMH_BASE",
                "ACOM_DMH_HIS",
                "ACOM_EPB_BASE",
                "ACOM_EPB_HIS",
                "ACOM_EPB_ITM",
                "ACOM_ERR_MSG_CD",
                "ACOM_FAB_BASE",
                "ACOM_FAB_HIS",
                "ACOM_FAB_ITM",
                "ACOM_FRE_RPT01",
                "ACOM_FRE_RPT02",
                "ACOM_FRE_RPT03",
                "ACOM_FRE_RPT04",
                "ACOM_FRE_RPT05",
                "ACOM_FRE_RPT06",
                "ACOM_FRE_RPT07",
                "ACOM_FRE_RPT08",
                "ACOM_FRE_RPT09",
                "ACOM_LMT_APL",
                "ACOM_LMT_BASEACT",
                "ACOM_LMT_BASEHD",
                "ACOM_LMT_BASEHIS",
                "ACOM_LMT_BOJ",
                "ACOM_LMT_ITM",
                "ACOM_LMT_SIL",
                "ACOM_LMT_SILHIS",
                "ACOM_LOSTLC_BASE",
                "ACOM_LOSTLC_INF",
                "ACOM_MIJI_BASE",
                "ACOM_MISU_BASE",
                "ACOM_MISU_HIS",
                "ACOM_MISU_HOISU",
                "ACOM_OVRD_APL",
                "ACOM_OVRD_HIS",
                "ACOM_REH_ACPROOF",
                "ACOM_REH_BOPCH",
                "ACOM_REH_CODE",
                "ACOM_REH_DOCINFO",
                "ACOM_REH_HIS",
                "ACOM_REH_HKMA",
                "ACOM_REH_HKMA13",
                "ACOM_REH_HKMAINFO",
                "ACOM_REH_HQ0008",
                "ACOM_REH_HQ0009",
                "ACOM_REH_HQ0010",
                "ACOM_REH_HQ0016",
                "ACOM_REH_INFO",
                "ACOM_REH_LARGEAMT",
                "ACOM_REH_NYFNDTRX",
                "ACOM_REH_NYINVEST",
                "ACOM_REH_NYPROOF",
                "ACOM_REH_REPACT",
                "ACOM_REH_SUSPTRAN",
                "ACOM_REQ_BASE",
                "ACOM_REQ_HIS",
                "ACOM_RES_KEY",
                "ACOM_SIS_SEQ",
                "ACOM_SYS_INFO",
                "ACOM_SYS_MSGS",
                "ACOM_SYS_MSGUSES",
                "ACOM_TKH_AMT91",
                "ACOM_TKH_AMT92",
                "ACOM_TKH_AMT991",
                "ACOM_TKH_AMT992",
                "ACOM_TKH_AMT993",
                "ACOM_TKH_AMT9991",
                "ACOM_TKH_AMT9992",
                "ACOM_TKH_BASE",
                "ACOM_TKH_CHAR",
                "ACOM_TKH_CUR1",
                "ACOM_TKH_CUR2",
                "ACOM_TKH_DATE",
                "ACOM_TKH_FIX",
                "ACOM_TKH_JRNL",
                "ACOM_TKH_JULI",
                "ACOM_TKH_MODA",
                "ACOM_TKH_MON",
                "ACOM_TKH_PREVAR1",
                "ACOM_TKH_PREVAR2",
                "ACOM_TKH_WBANK",
                "ACOM_TKH_WEDA",
                "ACOM_TKH_WEEK",
                "ACOM_TKH_WEMO",
                "ACUS_CNTCT_CTT",
                "ACUS_CNTCT_HIS",
                "ADST_BI_CODE",
                "ADST_CKB_BASE",
                "ADST_CKB_DROK",
                "ADST_CKB_HIS",
                "ADST_CKB_TOT",
                "ADST_DIH_BASE",
                "ADST_DIH_HIS",
                "ADST_DOH_BASE",
                "ADST_DOH_BASE_TEMP3",
                "ADST_DOH_BASE_TMP2",
                "ADST_DOH_HIS",
                "ADST_DOH_HIS_TEMP3",
                "ADST_DOH_HIS_TMP2",
                "ADST_DPB_BASE",
                "ADST_DPB_BUDO",
                "ADST_DPB_BURI",
                "ADST_DPB_CHCK",
                "ADST_DPB_DROK",
                "ADST_DPB_EXTN",
                "ADST_DPB_GYUL",
                "ADST_DPB_HEJI",
                "ADST_DPB_INFO",
                "ADST_DPB_INRT",
                "ADST_DPB_LNIF",
                "ADST_DPB_TADDR",
                "ADST_DPB_TAJM",
                "ADST_DPB_TAX",
                "ADST_DPB_YEDE",
                "ADST_DT_INFO_MSG",
                "ADST_GTB_BASE",
                "ADST_GTB_HIS",
                "ADST_GTB_INT",
                "ADST_LLG_TEMP",
                "ADST_LNB_AGR",
                "ADST_LNB_BASE",
                "ADST_LNB_FEE",
                "ADST_LNB_HIS",
                "ADST_LNB_INT",
                "ADST_LNB_ITM",
                "ADST_LNB_LRPT",
                "ADST_LNB_MSB",
                "ADST_LNB_MSH",
                "ADST_LNB_REPAY",
                "ADST_LNB_SCH",
                "AEBK_EBH_AMT",
                "AEBK_EBH_BASE",
                "AEBK_EBH_CRINF",
                "AEBK_EBH_LMT",
                "AEBK_EBH_PROK",
                "AEBK_EBH_TRM",
                "AFEX_ADH_AMEND",
                "AFEX_ADH_BASE",
                "AFEX_ADH_FAXMSG",
                "AFEX_ADH_HIS",
                "AFEX_ADH_ITM",
                "AFEX_ADH_TRANS",
                "AFEX_CBB_ADV",
                "AFEX_CBB_BASE",
                "AFEX_CBB_BDB",
                "AFEX_CBB_BDS",
                "AFEX_CBB_HIS",
                "AFEX_CBH_CA",
                "AFEX_CHANGE_BI_CODE",
                "AFEX_DIH_BASE",
                "AFEX_DOH_BASE",
                "AFEX_DOH_HIS",
                "AFEX_EXB_BASE",
                "AFEX_EXB_IHGM",
                "AFEX_EXB_SILM",
                "AFEX_IPB_AMD",
                "AFEX_IPB_BASE",
                "AFEX_IPB_BLD",
                "AFEX_IPB_BLK",
                "AFEX_IPB_BOJ",
                "AFEX_IPB_COR",
                "AFEX_IPB_DJB",
                "AFEX_IPB_DJH",
                "AFEX_IPB_DPDA",
                "AFEX_IPB_FEE",
                "AFEX_IPB_HIS",
                "AFEX_IPB_ITM",
                "AFEX_IPB_JAJ",
                "AFEX_IPB_LGM",
                "AFEX_IPH_AMD",
                "AFEX_IPH_ATAG",
                "AFEX_IPH_BASE",
                "AFEX_IPH_BTAG",
                "AFEX_IPH_COR",
                "AFEX_IPH_COVER",
                "AFEX_IPH_HIS",
                "AFEX_NRH_BASE",
                "AFEX_NRH_HIS",
                "AFEX_POH_BASE",
                "AFEX_POH_HIS",
                "AFEX_POH_MT100",
                "AFEX_POH_MT752",
                "AFEX_POH_MT754",
                "AFEX_RAH_AMD",
                "AFEX_RAH_BASE",
                "AFEX_RAH_BDS",
                "AFEX_RAH_CLM",
                "AFEX_RAH_HIS",
                "AFEX_RCH_BAL",
                "AFEX_RCH_BASE",
                "AFEX_RCH_PEND",
                "AFEX_RCH_RECON",
                "AFEX_RCH_SEQNO",
                "AFEX_RCH_TRAN",
                "AFEX_RCH_VOSTRO",
                "AFEX_RIA_BASE",
                "AFEX_RIA_HIS",
                "AFEX_RIB_BASE",
                "AFEX_RIB_HIS",
                "AFEX_RIB_MAEIB",
                "AFEX_RIH_BASE",
                "AFEX_RIH_HIS",
                "AFEX_ROB_AMD",
                "AFEX_ROB_BASE",
                "AFEX_ROB_HIS",
                "AFEX_ROB_IGL",
                "AFEX_ROB_SNG",
                "AFEX_ROH_BASE",
                "AFEX_ROH_HIS",
                "AFEX_RTB_BASE",
                "AFEX_RTB_BUYSELL",
                "AFEX_RTB_HIS",
                "AFEX_RTB_HSS",
                "AFEX_RTB_INTERBASE",
                "AFEX_RTB_REQ",
                "AFEX_RTB_REQMSE",
                "AFEX_RTB_TEMP",
                "AFEX_RTB_TOTAL",
                "AFEX_TCB_BASE",
                "AFEX_TCB_HIS",
                "AFEX_TCB_MSE",
                "AFEX_TCB_OSON",
                "AFEX_TCB_OSONMSE",
                "AFEX_TCB_REQ",
                "AFEX_TCB_REQMSE",
                "AFEX_TCB_SILM",
                "AFEX_TCB_SUDONG",
                "AFEX_TCB_TOTAL",
                "AFEX_XPB_ADV",
                "AFEX_XPB_AMD",
                "AFEX_XPB_BASE",
                "AFEX_XPB_BDM",
                "AFEX_XPB_BDS",
                "AFEX_XPB_HIS",
                "AFEX_XPB_ITM",
                "AFEX_XPB_LGM",
                "AFEX_XPB_RENEDT",
                "AFEX_XPH_CA",
                "AFEX_XPH_CCUT",
                "AFEX_XPH_COVER",
                "AFEX_XPH_COVER_RESEND",
                "AFEX_XPH_RENEGO",
                "AFEX_XPH_SHIP",
                "AFEX_XPH_SHIP_RESEND",
                "AFEX_XPH_TRA",
                "AFIF_BDH_BASE",
                "AFIF_BDH_DRAW",
                "AFIF_BDH_FEE",
                "AFIF_BDH_FEEPAY",
                "AFIF_BDH_HIS",
                "AFIF_BDH_INT",
                "AFIF_BDH_INTADJ",
                "AFIF_BDH_OPTION",
                "AFIF_BDH_REDEM",
                "AFIF_BDH_REPAY",
                "AFIF_BDH_SYN",
                "AFIF_COMH_HEDGE",
                "AFIF_CPH_BASE",
                "AFIF_CPH_HIS",
                "AFIF_CPH_OPTION",
                "AFIF_CPH_REVAL",
                "AFIF_FBH_AMORT",
                "AFIF_FBH_BASE",
                "AFIF_FBH_BONDTYPE",
                "AFIF_FBH_BUY",
                "AFIF_FBH_CBBW",
                "AFIF_FBH_CUSBASE",
                "AFIF_FBH_CUSHIS",
                "AFIF_FBH_CUSINT",
                "AFIF_FBH_CUSREPAY",
                "AFIF_FBH_DEAL",
                "AFIF_FBH_FEE",
                "AFIF_FBH_FEERCV",
                "AFIF_FBH_HIS",
                "AFIF_FBH_INT",
                "AFIF_FBH_INTADJ",
                "AFIF_FBH_OPTION",
                "AFIF_FBH_REDEM",
                "AFIF_FBH_REPAY",
                "AFIF_FBH_RESTRUCT",
                "AFIF_FBH_REVAL",
                "AFIF_FDH_BASE",
                "AFIF_FDH_DRAW",
                "AFIF_FDH_FEE",
                "AFIF_FDH_FEEPAY",
                "AFIF_FDH_HIS",
                "AFIF_FDH_INT",
                "AFIF_FDH_INTADJ",
                "AFIF_FDH_OPTION",
                "AFIF_FDH_REPAY",
                "AFIF_FDH_REPO",
                "AFIF_FDH_SYN",
                "AFIF_FEH_BASE",
                "AFIF_FEH_BLOTTER",
                "AFIF_FEH_CCYPOS",
                "AFIF_FEH_DEALERPL",
                "AFIF_FEH_DEALERPOS",
                "AFIF_FEH_HIS",
                "AFIF_FEH_ILDEALPL",
                "AFIF_FEH_REVAL",
                "AFIF_FEH_TOTALPOS",
                "AFIF_FGH_BASE",
                "AFIF_FGH_FEERCV",
                "AFIF_FGH_GRTREPAY",
                "AFIF_FGH_HIS",
                "AFIF_FIF_CUST",
                "AFIF_FNH_BASE",
                "AFIF_FNH_DRAW",
                "AFIF_FNH_FEE",
                "AFIF_FNH_FEERCV",
                "AFIF_FNH_HIS",
                "AFIF_FNH_INT",
                "AFIF_FNH_INTADJ",
                "AFIF_FNH_OPTION",
                "AFIF_FNH_REPAY",
                "AFIF_FNH_RESTRUCT",
                "AFIF_FNH_SYNBANK",
                "AFIF_FNH_SYNBASE",
                "AFIF_FNH_SYNDRWRPY",
                "AFIF_FNH_SYNFEE",
                "AFIF_FNH_SYNHIS",
                "AFIF_FNH_SYNINT",
                "AFIF_MMH_BASE",
                "AFIF_MMH_HIS",
                "AFIF_MMH_HR",
                "AFIF_MMH_HRHIS",
                "AFIF_MMH_INT",
                "AFIF_MMH_LINE",
                "AFIF_MTH_BASE",
                "AFIF_MTH_HIS",
                "AFIF_SPH_BASE",
                "AFIF_SPH_HIS",
                "AFIF_SPH_REVAL",
                "AFIF_SWH_AMORT",
                "AFIF_SWH_BASE",
                "AFIF_SWH_CLOSE",
                "AFIF_SWH_HIS",
                "AFIF_SWH_INT",
                "AFIF_SWH_INTADJ",
                "AFIF_SWH_REPAY",
                "AFIF_SWH_REVAL",
                "AFTR_FFH_ACCT_BY_SAPV_DTLS",
                "AFTR_FFH_AMT_INVL_BY_DTLS",
                "AFTR_FFH_APV_BY_SAPV_DTLS",
                "AFTR_FFH_ARDC_RANG_DTLS",
                "AFTR_FFH_BR_BY_SAPV_DTLS",
                "AFTR_FFH_COMM_BASE",
                "AFTR_FFH_COMM_GRP_BASE",
                "AFTR_FFH_COMM_NLVYD_PTCL",
                "AFTR_FFH_COMM_RADJ_HIST",
                "AFTR_FFH_COMM_SAPV_OPI_DTLS",
                "AFTR_FFH_COMM_TRSC_AD_DTLS",
                "AFTR_FFH_CRDT_GRD_BY_DTLS",
                "AFTR_FFH_CUST_BY_SAPV_DTLS",
                "AFTR_FFH_CUST_GRD_PRIM_DTLS",
                "AFTR_FFH_ETC_CALS_BY_DTLS",
                "AFTR_FFH_EVNT_PTCL",
                "AFTR_FFH_INQ_COMM_TRSC_PTCL",
                "AFTR_FFH_PCSE_DTLS",
                "AFTR_FFH_PRD_BY_PRIM_DTLS",
                "AFTR_FFH_PRIM_BY_TGT_DTLS",
                "AFTR_FFH_PRIM_RSN_LIST_BASE",
                "AFTR_FFH_RADJ_COMM_DTLS",
                "AFTR_FFH_RDU_BY_PRIM_DTLS",
                "AFTR_FFH_SAPV_APC_ADTN_DTLS",
                "AFTR_FFH_SAPV_APC_APV_BASE",
                "AFTR_FFH_SAPV_APC_DTLS",
                "AFTR_FFH_SQN_BY_PRIM_DTLS",
                "AFTR_FFH_TRM_BY_DTLS",
                "AFTR_FFH_WDAY_DRTM_BY_DTLS",
                "AFTR_PFH_BASE",
                "AFTR_PFH_BR_BASE",
                "AFTR_PFH_BR_DTLS",
                "AFTR_PFH_CHNL_BASE",
                "AFTR_PFH_CHNL_DTLS",
                "AFTR_PFH_CLAS_CD",
                "AFTR_PFH_INST_BASE",
                "AFTR_PFH_LIM_BASE",
                "AFTR_PFH_LIM_CD",
                "AFTR_PFH_LIM_DTLS",
                "AFTR_PFH_MPPG_BASE",
                "AFTR_PFH_MPPG_CD",
                "AFTR_PFH_MPPG_DTLS_CD",
                "AFTR_PFH_NM_DTLS",
                "AFTR_PFH_TRCN_BASE",
                "AFTR_PFH_TRCN_CD",
                "AFTR_PFH_TRCN_CD_REL",
                "AFTR_PFH_TRCN_DTLS",
                "AFTR_PFH_TRCN_DTLS_CD",
                "AFTR_PFH_TRCN_DTLS_REL",
                "AFTR_PFH_TRCN_REL",
                "APDF_PFH_BASE",
                "APDF_PFH_BR_BASE",
                "APDF_PFH_BR_DTLS",
                "APDF_PFH_CHNL_BASE",
                "APDF_PFH_CHNL_DTLS",
                "APDF_PFH_CLAS_CD",
                "APDF_PFH_INST_CD",
                "APDF_PFH_LIM_BASE",
                "APDF_PFH_LIM_CD",
                "APDF_PFH_NM_DTLS",
                "IFRS_DD_BY_CFLW_DPRC_PTCL",
                "IFRS_DD_BY_CFLW_INP_BASE",
                "IFRS_DD_BY_CFLW_RSLT_PTCL",
                "IFRS_DD_BY_TRSC_BASE",
                "IFRS_DD_BY_VALD_INT_PTCL",
                "IFRS_PSTPN_COMM_TRSC_PTCL",
                "JUN_TBL",
                "MAN_TABLE",
                "NCODE_LIST",
                "NCOL_LIST",
                "ADST_LNB_NPL_BASE",
                "ADST_LNB_NPL_INT",
                "ADST_LNB_NPL_REPAY",
                "ADST_LNB_ITM2",
                "ADST_PMM_CTT",
                "ADST_PMM_BASE",
                "ADST_APM_APPUSER",
                "ADST_CAH_HGRDN",
                "ADST_APM_APPRVMAIN",
                "ADST_APM_APPRV",
                "ADST_APM_SGSUB",
                "ADST_APM_PRGSS",
                "ADST_APM_EXPOS",
                "ADST_APM_BKTRN",
                "ADST_APM_JOURNAL_COMP",
                "ADST_APM_JOURNAL",
                "ADST_APM_OPN2",
                "ADST_APM_OPN1",
                "ADST_APM_OPER",
                "ADST_APM_JOURNAL_ETC",
                "ADST_APM_PORTP",
                "ADST_APM_PAPER",
                "ADST_APM_SNGCD",
                "ADST_APM_SGHIS",
                "ADST_APM_VOTEHIS",
                "ADST_APM_VOTE",
                "ADST_APM_TEMP2",
                "ADST_APM_DAMBO",
                "ADST_APM_TEMP1",
                "ADST_DPB_GYTMP",
                "ACOM_COMH_REFALLOW",
                "MIG_GTB_BASE",
                "AACT_AMORT_HIS",
                "ACOM_REH_SID_DIN_MSE",
                "ACOM_REH_SID_DIN_FOOT",
                "ACOM_REH_SID_DIN_BASE",
                "ACOM_REH_SID_FM03C",
                "TRD_S_KREDIT00",
                "AFTR_PFH_LIM_RSLT",
                "ACOM_EPB_RPT",
                "ACOM_COMH_IMG",
                "AACT_TRX_OVRDBASE",
                "AACT_TRX_OVRDITM",
                "ACOM_ATB_ETCTRNS",
                "ACOM_COMH_REFCOLHIS",
                "ACOM_CODE_HIS",
                "AEBK_EBH_BLK",
                "ADST_LNB_ITM3",
                "ADST_DPB_YDLST",
                "ACOM_COMH_GROUP_LMTRT",
                "ACOM_SYS_HDWARE",
                "ACOM_COM_EXCEL",
                "MRTP_RE62_CM006",
                "ISYS_DAT_ACCT_ADJ_PTCL",
                "ISYS_DAT_ACCT_BAL_PTCL",
                "MRTP_RE62_CM900",
                "ACOM_BIX_INFO",
                "MRTP_RE62_CM303",
                "ICOM_IFH_ADTRPT",
                "ACOM_COMH_USERREL",
                "MRTP_RE62_CM250",
                "MRTP_RE62_CM602",
                "AACT_TRX_BASE_DR",
                "AEBK_EIH_MAP",
                "AEBK_EIH_CNTS",
                "AEBK_HSM_BASE",
                "AEBK_HSM_HIS",
                "ACOM_SCAN_HIS",
                "ACOM_CIX_BSTYPE",
                "AEBK_EBH_CLAIM",
                "AFIF_BI_INFO",
                "MRTP_RE62_CM253",
                "ACOM_COM_FXINFO",
                "ACOM_COMH_UMSMSG",
                "ACOM_COMH_UMSDATA",
                "AEBK_ECH_BASE",
                "AEBK_ECH_DROK",
                "AEBK_ECH_USER",
                "AEBK_EOH_SEQ",
                "ACOM_COMH_RNDM",
                "ACOM_CIX_MSGINFO",
                "ACOM_MENU_FVRT",
                "ACOM_SCNRO_BASE",
                "ACOM_SCNRO_DTLS",
                "AFBK_FKH_BAT_TR_BASE",
                "AFBK_FKH_CONT_UPD_PTCL",
                "AFBK_FKH_NOGT_PTCL",
                "AFBK_FKH_NTFY_TRMS_PTCL",
                "AFBK_FKH_CONT_BASE",
                "AFBK_FKH_BAT_TR_PTCL",
                "ACOM_PSH_BASE",
                "ACOM_PSH_HIS",
                "ACOM_PSH_VTNO_BASE",
                "ACOM_PSH_VTNO_TRAN",
                "MRTP_RE62_CM255",
                "ACOM_COMH_USERKEY",
                "AEBK_EOH_TRAN",
                "AEBK_ECH_CONT_DTLS",
                "AEBK_ECH_CORP_REL",
                "AEBK_ECH_AUTH",
                "AEBK_ECH_CONT_BASE",
                "AEBK_ECH_CONT_ACCT",
                "AEBK_ECH_CONT_UPD_PTCL",
                "AEBK_ECH_BAT_TR_BASE",
                "AEBK_ECH_BAT_TR_PTCL",
                "ACOM_COMH_TRRST",
                "ACOM_COMH_TRRST_ITM",
                "ACOM_COMH_MSG_R",
                "ACOM_COMH_MSGHIS_R",
                "ACOM_COMH_TAGLINE_R",
                "AEBK_ECH_BAT_REMIT_BASE",
                "AEBK_ECH_BAT_REMIT_PTCL",
                "ACOM_COM_EXRT2",
                "ADST_DPB_GIFT",
                "AFIF_FEH_CCYPOSTERM",
                "ACOM_LMT_CRLINE",
                "ACOM_LMT_CRLINEHIS",
                "AACT_TRX_ACTLOG_BF",
                "ACOM_ATB_MAP",
                "AFIF_FEH_DEALERPOSTM",
                "ACOM_ATB_UPLOAD_INFO",
                "ACOM_COM_PRIMEXRT",
                "AACT_TRX_PRIMEXRT",
                "NCODE_MAPPING_TEMP",
                "NCODE_MAPPING_TEMP_BACK",
                "NTBL_MAPPING",
                "NTBL_MAPPING_BACK",
                "ACOM_COM_CHREF_MIG",
                "AACT_ACT_DATE_HANA",
                "AACT_ACT_DATE_KEB",
                "ACOM_COM_CB_PEXRT",
                "ACOM_GCIX_BASE",
                "AFTR_FFH_CB_PCOMM",
                "AACT_OTB_TAX_MSE",
                "AEBK_ECH_KINET_HIS",
                "AACT_ACR_BAL_BK",
                "AACT_ACR_BASE_BK",
                "AACT_ACR_HIS_BK",
                "AACT_ACR_TRAN_BK",
                "AACT_TRX_BAL_BK",
                "AACT_TRX_PL_BK",
                "AACT_ACT_DATE_KEB_BK",
                "ACOM_CIX_DUPMNG_MIG",
                "ACOM_DMB_APPR",
                "ACOM_DMB_APPRINS",
                "ACOM_DMB_APPRITEM",
                "ACOM_DMB_BASE",
                "ACOM_DMB_CUST",
                "ACOM_DMB_GNTE",
                "ACOM_DMB_INSR",
                "ACOM_COM_CUSTCHG",
                "ACOM_COM_CUSTCHG_HIS",
                "ACOM_COMH_USERWB",
                "AFBK_FKH_BAT_REMIT_PTCL",
                "AFBK_FKH_CONT_DTLS",
                "AFBK_FKH_BAT_FX_PTCL",
                "AFBK_FKH_BAT_TR_DTLS",
                "AFIF_FIF_PRD_DTLS",
                "AFIF_FIF_CONT_DTLS",
                "ACOM_DMB_PLG",
                "ACOM_DMB_CLPLG",
                "ACOM_DMB_CLGNAPPR",
                "ACOM_DMB_BASE_MIG",
                "ACOM_DMB_GNTE_MIG",
                "MRTP_RE62_CM256",
                "MRTP_RE62_CM257",
                "ICOM_IFH_ADTRPT2",
                "ACOM_COMH_USERSTS",
                "AACT_ACT_DATE2",
                "ADST_ENB_CONT_HIS",
                "ADST_ENB_ENT_REL",
                "ADST_ENB_ITM",
                "ADST_ENB_BOND_HIS",
                "AFIF_FEH_FWD_MRGN",
                "ADST_ENB_CONT_BASE",
                "AACT_ATM_DATE",
                "ACOM_CIX_PYRL",
                "ADST_CAN_ACCT",
                "ADST_CAN_BRWINFO",
                "ADST_CAN_CAINFO",
                "ADST_CAN_CARCPT",
                "ADST_CAN_CARTG",
                "ADST_CAN_CASCO",
                "ADST_CAN_CAUNIT",
                "ADST_CAN_CPAOPN",
                "ADST_CAN_CVTRTG",
                "ADST_CAN_DPSTTR",
                "ADST_CAN_ECAIRTG",
                "ADST_CAN_FNLOPN",
                "ADST_CAN_FNPRJCT",
                "ADST_CAN_FNSTMT",
                "ADST_CAN_FNSTMT_T",
                "ADST_CAN_FNTR",
                "ADST_CAN_HISTORY",
                "ADST_CAN_MNGINFO",
                "ADST_CAN_PRJCTRTO",
                "ADST_CAN_SHRHLD",
                "ADST_CAN_SLBYER",
                "ADST_CAN_SLPCMTHD",
                "ADST_CAN_SLSINFO",
                "ADST_CAN_TRADTR",
                "ADST_CAN_TRANHIS",
                "ADST_CAN_AUTHLINE",
                "ACOM_CIX_DOC",
                "AFEX_RCH_TEMP",
                "AEBK_EBH_LMTEXPT",
                "ADST_ENB_CONT_ACCT",
                "ACOM_PSH_VTNO_HIS",
                "ACOM_PSH_VTNO_INFO",
                "AEBK_SMSH_BASE",
                "AEBK_EBH_EDCM_RECON",
                "AEBK_EBH_CLAIM_HIS",
                "AEBK_BLL_BASE",
                "AEBK_ECH_ETC_APC_PTCL",
                "AEBK_ECH_ETC_PRGR_BASE",
                "ACOM_ATB_LOCK",
                "ACOM_ATB_LOCK_HIS",
                "ACOM_CIX_GRP_DTLS",
                "ACOM_CIX_GRP",
                "ADST_WFL_BASE",
                "ADST_WFL_CUSTCHG",
                "ADST_WFL_DTLS",
                "ADST_WFL_FILE",
                "ADST_WFL_GRANT",
                "ADST_WFL_HIS",
                "ADST_WFL_OPN",
                "ADST_WFL_PROC",
                "AEBK_BLL_PTCL",
                "ADST_ENB_LN_INFO",
                "ADST_DPB_LNINT",
                "ACUS_CNTCT_BNFT",
                "AFEX_ROH_MOD_GIBI",
                "AEBK_EBH_REDEEM",
                "ADST_LNB_ETC_INFO",
                "ADST_WMB_TMP",
                "AEBK_WMB_INTR",
                "AEBK_ECH_ETC_APC_OCR",
                "ADST_DPB_KRNO",
                "ACOM_DMB_ACCTPARM",
                "ACOM_DMB_CLAPR",
                "ACOM_DMB_CLAPRPARM",
                "ACOM_DMB_CLDPEVAL",
                "ACOM_DMB_CLDV",
                "ACOM_DMB_CLGNTE",
                "ACOM_DMB_CLPARM",
                "ACOM_DMB_CLRT",
                "ACOM_DMB_CRDTANAL",
                "ACOM_DMB_RSVMST",
                "ACOM_DMB_SDCLEVL",
                "ACOM_TBBS_WLIST",
                "ACOM_TBBS_WLISTFACTIVAOSN",
                "ACOM_TBBS_WLISTFACTIVAOTH",
                "ACOM_TBBS_WLISTHIST",
                "ACOM_COMH_DEBTORINFO",
                "ACOM_COMH_ACTIVITY",
                "ADST_SIDOC_BASE",
                "ACOM_CIX_QUEST",
                "ACOM_COMH_PWKEY",
                "ADST_OQT_BASE",
                "AEBK_ECH_LNB_APC_BASE",
                "ACOM_FAB_DTLS",
                "AEBK_EBH_PROD_BASE",
                "AFIF_FEH_BLOTTER2",
                "AEBK_EIH_FFX_BASE",
                "AEBK_EIH_FFX_CONT",
                "MRTP_RE62_CM251",
                "ACOM_CIX_CONFLETTER",
                "ADST_LNB_GRNTEE_LTR",
                "AEBK_ECH_ETC_APC_BASE",
                "STAT161216",
                "ADST_ENB_BOND_BASE",
                "EC25_HIS_TRX_DEBIT_INQ",
                "ADST_WMB_BAL",
                "ADST_WMB_HIS",
                "AFBK_FKH_BAT_EN_PTCL",
                "TEMP_DATA",
                "TEMP_DATA_TEST_JAN17",
                "AFEX_REMIT_TEMP",
                "ADST_WFB_CSM_BASE",
                "ADST_WFL_BICHECK",
                "ADST_ENB_LMT_CONT",
                "AEBK_EIH_RISK_NOTIF",
                "ADST_CAN_CUSTINFO",
                "AEBK_EIH_BAT_HIS",
                "ADST_CAN_ACCT_DFI",
                "TBCR_BAT_SCHEDULER",
                "TBCR_BAT_SCHEDULER_HIS",
                "TBCR_EWBATCH",
                "TBCR_EWCHNGAGGR",
                "TBCR_EWCLLTR",
                "TBCR_EWCUSTOB_BASE",
                "TBCR_EWCUSTOB_DEFECTIVE",
                "TBCR_EWDELAY",
                "TBCR_EWDPAJAN",
                "TBCR_EWEXAM",
                "TBCR_EWEXAMITEM",
                "TBCR_EWEXAMITEMDTL",
                "TBCR_EWEXAMPRD",
                "TBCR_EWEXAMRLT",
                "TBCR_EWEXCL",
                "TBCR_EWEXCLITEM",
                "TBCR_EWEXEC",
                "TBCR_EWEXECITEM",
                "TBCR_VALUE",
                "TBCR_EWFNSTMT",
                "TBCR_EWFSMTAUDIT",
                "TBCR_EWGRDAGGR",
                "TBCR_EWSUBJ",
                "TBCR_LRRCCD",
                "TBCR_AUTHLINE",
                "TBCR_LRADMIN",
                "TBCR_LRCUST",
                "TBCR_LRFDCD",
                "TBCR_LRIPLM",
                "TBCR_LRLIST",
                "TBCR_LROPINION",
                "TBCR_EWAPPRV",
                "TESTING1234",
                "AEBK_ECH_CORP_DEBT_REL",
                "EC25_HIS_TRX_CORP_DEBIT_INQ",
                "AEBK_EBH_CORP_BASE",
                "FBCD_BANCA_SUBS_BASE",
                "FBCD_BANCA_CONT_BASE",
                "FBCD_BANCA_TRSC_HST",
                "FBCD_BANCA_FUND_IVT_INFO",
                "FBCD_BANCA_DALY_BALS_HST",
                "FBCD_BANCA_CONT_CUST",
                "FBCD_BANCA_INSURAL_CUST",
                "FBCD_BANCA_BENFY_CUST",
                "FBCD_BANCA_ACCD_HST",
                "FBCD_BANCA_PROD_BASE",
                "FBCD_BANCA_FEE_RATE",
                "FBCD_BANCA_RIDER_INFO",
                "FBCD_BANCA_PRODUCT_DATA",
                "TEMP_MST_ADDRESSES",
                "TEMP_MST_ANSWERS",
                "TEMP_MST_BRANCHES",
                "TEMP_MST_CONTACTS",
                "TEMP_MST_CUSTODIANS",
                "TEMP_MST_CUSTODIAN_ADDRESSES",
                "TEMP_MST_CUSTODIAN_CONTACTS",
                "TEMP_MST_CUSTOMERS",
                "TEMP_MST_CUSTOMER_IDS",
                "TEMP_MST_DOCUMENTS",
                "TEMP_MST_INVESTMENT_ACCOUNTS",
                "TEMP_MST_INV_HOLDERS",
                "TEMP_MST_INV_SINVEST_MAPPING",
                "TEMP_MST_LOOKUP_DETAILS",
                "TEMP_MST_PRODUCT_TYPES",
                "TEMP_MST_QUESTIONNAIRES",
                "TEMP_MST_QUESTIONS",
                "TEMP_MST_SALES",
                "TEMP_MST_SALES_CERTIFICATIONS",
                "TEMP_MST_SCORES",
                "TEMP_MST_SCORE_COMPOSITIONS",
                "TEMP_MST_SETTLEMENT_ACCOUNTS",
                "TEMP_MST_TRX_PROCESS_FLOWS",
                "TEMP_MST_UT_CUSTOMER_SEGMENTS",
                "T_MST_UT_DISTRIBUTION_BRANCHES",
                "TEMP_MST_UT_FEE_STRUCTURES",
                "TEMP_MST_UT_FEE_TIERS",
                "T_MST_UT_INVESTMENT_MANAGERS",
                "TEMP_MST_UT_PRODUCTS",
                "TEMP_REPORT_RECONCILE_CUST_BAL",
                "T_REPORT_RECONCILE_TRANSACTION",
                "TEMP_REPORT_RM_PERFORMANCE",
                "TEMP_TRX_CUSTOMER_ANSWERS",
                "TEMP_TRX_DETAILS",
                "TEMP_TRX_SETTLEMENTS",
                "T_TRX_SETTLEMENT_INTEGRATIONS",
                "TEMP_TRX_UT_ACCOUNT_BALANCES",
                "TEMP_TRX_UT_ADJUSTMENTS",
                "TEMP_TRX_UT_CANCELLATIONS",
                "TEMP_TRX_UT_DOCUMENTS",
                "TEMP_TRX_UT_FUND_PRICES",
                "T_TRX_UT_HIST_ACCOUNT_BALANCES",
                "TEMP_TRX_UT_HIST_FUND_PRICES",
                "TEMP_TRX_UT_MANUAL_RECONCILES",
                "TEMP_TRX_UT_REDEMPTION_LINES",
                "TEMP_TRX_UT_RSP_DOCUMENTS",
                "TEMP_TRX_UT_RSP_SETUPS",
                "TEMP_TRX_UT_SUBSCRIPTION_LINES",
                "TEMP_TRX_UT_TRANSACTIONS",
                "KEWS11_CUSTOMER",
                "KEWS12_CUSTOMER_REL",
                "KEWS01_USER",
                "KEWS34_EVAL_ITEMPROFILE",
                "KEWS22_RESULT_ITEM",
                "KEWS31_EVAL_PROCESS",
                "IDEB31_CREDITS",
                "IDEB21_CORPORATEDEBTORS",
                "IDEB20_CORPORATE",
                "IDEB34_BANKGUARANTEES",
                "KEWS35_EVAL_IDEBPROFILE",
                "IDEB10_INDIVIDUAL",
                "KEWS32_EVAL_CUSTOMER",
                "IDEB22_CORPORATEOWNER",
                "IDEB32_LCS",
                "KEWS21_RESULT_CUSTOMER",
                "IDEB30_FACILITYSUMMARY",
                "KEWS02_CODE",
                "IDEB35_OTHERS",
                "IDEB41_COLLATERALS",
                "IDEB02_SUMMARY",
                "IDEB42_GUARANTORS",
                "IDEB11_INDIVIDUALDEBTORS",
                "IDEB33_SECURITIES",
                "AFIF_FBH_SELLPLAN",
                "X_ACOM_REH_REPORT",
                "AEBK_ECH_ETC_APC_EXT1",
                "AEBK_ECH_ETC_APC_REL",
                "AEBK_ECH_SCH_BNK",
                "AEBK_ECH_SCH_BNK_STDN",
                "AEBK_ECH_SCH_BNK_HIS",
                "AEBK_ECH_SCH_BNK_STDN_HIS",
                "ACOM_SCAN_VALID",
                "FBCD_BST_BUY_APPL",
                "FBCD_BST_BUY_BAL",
                "FBCD_BST_CONV_APPL",
                "FBCD_BST_DIVD_ACCT",
                "FBCD_BST_DRAW_DETL",
                "FBCD_BST_DRAW_HST",
                "FBCD_BST_REPC_APPL",
                "FBCD_BST_REWRD_HST",
                "FBCD_BST_TAX",
                "FBCD_BST_TRD_HST",
                "FBCD_COM_BATCH",
                "FBCD_COM_RULE",
                "FBCD_COM_RULE_GRP",
                "FBCD_COT_BATCH_ACCT_HST",
                "FBCD_COT_BATCH_HST",
                "FBCD_CUM_ACCT",
                "FBCD_CUM_ACCT_MAPPING",
                "FBCD_CUM_MOM_ACCT",
                "FBCD_CUM_MOM_ACCT_MAPPING",
                "FBCD_CUST_ADD_INFO",
                "FBCD_CUST_SURV_REPY_BASE",
                "FBCD_CUST_SURV_REPY_RES",
                "FBCD_CUT_ACCD_HST",
                "FBCD_INT_PROPT_QUE_BASE",
                "FBCD_INT_PROPT_QUE_DETL",
                "FBCD_RISK_PROF_QUE_BASE",
                "FBCD_RISK_PROF_QUE_DETL",
                "FBCD_SALE_BRNCH",
                "FBCD_SALE_USER",
                "FBCD_SAM_BAS_PRICE",
                "FBCD_SAM_FEE_RATE",
                "FBCD_SAM_FUND",
                "FBCD_SAM_WRKG_COMP",
                "FBCD_SAT_CNFM",
                "FBCD_SAT_DIVD_HST",
                "FBCD_SIT_BRAN_BAL",
                "FBCD_SIT_FUND_BAL",
                "FBCD_PROD_SALE_BRNCH",
                "FBCD_KSEI_UNIT_ACCT_BAL",
                "FBCD_ACCT_KSEI_BAL_RESULT",
                "FBCD_CLIENT_CD_NUMBER",
                "FBCD_COM_LOG",
                "FBCD_COM_LOG_NUM",
                "FBCD_COM_BRNCH",
                "FBCD_SALE_USER_DETL",
                "FBCD_BOND_CLOSING_PRICE",
                "FBCD_BOND_PRODUCT_DATA",
                "FBCD_BOND_CUM_ACCT",
                "FBCD_BOND_SELL_APC_SETL",
                "FBCD_BOND_ACCD_HST",
                "FBCD_BOND_CUM_MOM_ACCT",
                "FBCD_BOND_TRD_HST",
                "FBCD_BOND_BUY_APC_BAL",
                "FBCD_BOND_PROD_BASE",
                "FBCD_BOND_CUST_ADD_INFO",
                "FBCD_BOND_ACCT_BAL",
                "FBCD_BOND_FEE_RATE",
                "FBCD_BOND_COUPON_MATURITY",
                "FBCD_BOND_PROD_SALE_BRNCH",
                "ACOM_KEB_SYSTEM",
                "ACOM_CIX_FNSTMT",
                "ACOM_CIX_FNSTMT_ITM",
                "ADST_LNB_RGSTR",
                "AEBK_ECH_HFC_DEBT_REL",
                "ACOM_COMH_SUSPC",
                "ACOM_COMH_SUSPC_ITM",
                "ACOM_CIX_PIC",
                "ADST_LNB_BICHECK",
                "ACOM_COM_MARKET_HOLI",
                "ADST_CCARD_BILLING",
                "ADST_CCARD_UPLOAD",
                "ADST_CCARD_BASE",
                "ADST_EMB_BASE",
                "ADST_EMB_HIS",
                "AEBK_EBH_PRMO_PTCL",
                "AEBK_EBH_PRMO_BASE",
                "AEBK_EBH_PRMO_BAT_TR",
                "ADST_WFL_PRICE_BASE",
                "ADST_CAN_FILE",
                "AFTR_PFH_SUB_BASE",
                "ACOM_DMB_DEV",
                "EC25_HIS_TRX_HFC_DEBIT_INQ",
                "AEBK_EBH_HFC_BASE",
                "ACOM_COMH_SDCOMM",
                "AFIF_SDH_BASE",
                "AFIF_SDH_HIS",
                "AFIF_SDH_INT",
                "CFS_ITEM",
                "IDEBTB00_CONFIG",
                "IDEBTB01_REQUEST",
                "IDEBTB02_RECEIVE",
                "IDEBTB12_SUMMARY",
                "IDEBTB21_INDIVIDUAL",
                "IDEBTB22_INDIVIDUALDEBTORS",
                "IDEBTB25_CORPORATE",
                "IDEBTB26_CORPORATEDEBTORS",
                "IDEBTB27_CORPORATEOWNER",
                "IDEBTB30_FACILITYSUMMARY",
                "IDEBTB31_CREDITS",
                "IDEBTB33_SECURITIES",
                "IDEBTB34_LCS",
                "IDEBTB35_BANKGUARANTEES",
                "IDEBTB36_OTHERS",
                "IDEBTB41_COLLATERALS",
                "IDEBTB42_GUARANTORS",
                "IDEBTB03_RECEIVEDEBTORS",
                "CFS_TARGET",
                "CFS_PROFILE",
                "CFS_RESULT",
                "CFS_RESULTDTL",
                "AEBK_ECH_PAYBYQR_BASE",
                "ACOM_SHF_VTNO_INFO",
                "ADST_LNB_REPAYMENT",
                "FBCD_AID_BNCH_INDEX",
                "FBCD_AID_BR_STATISTIC",
                "FBCD_AID_ROBO_MNTN",
                "FBCD_AID_ROBO_MNTN_DTL",
                "FBCD_AID_ROBO_PKG_DEAL",
                "FBCD_AID_ROBO_PKG_DEAL_DTL",
                "FBCD_AID_ROBO_PLAN",
                "FBCD_AID_ROBO_PLAN_DTL",
                "FBCD_SAM_PRODUCT_DATA",
                "ADST_WFL_AUTO_APPR",
                "ADST_WFL_JOB_MNG",
                "ADST_WFL_OP_MNG",
                "AEBK_EBH_BSN_REDEEM_BASE",
                "ACOM_DMB_DEVHIS",
                "AEBK_TDS_ENROLL",
                "TMP_OTP",
                "ADST_ENB_STOP",
                "FBCD_ADJ_REPC_APPL",
                "ADST_CEB_ACCT",
                "ADST_CEB_APPRV",
                "ADST_CEB_BLGCD",
                "ADST_CEB_BNKADDFS",
                "ADST_CEB_BNKINFO",
                "ADST_CEB_BRWINFO",
                "ADST_CEB_CARCPT",
                "ADST_CEB_CASCO",
                "ADST_CEB_CASCODTL",
                "ADST_CEB_CMLFS",
                "ADST_CEB_CMLINFO",
                "ADST_CEB_CODE",
                "ADST_CEB_CPAOPN",
                "ADST_CEB_CUSTGRD",
                "ADST_CEB_CUSTINFO",
                "ADST_CEB_CVRTG",
                "ADST_CEB_DPSTTR",
                "ADST_CEB_ECAIRTG",
                "ADST_CEB_FEXRISK",
                "ADST_CEB_FNLOPN",
                "ADST_CEB_FNPRJCT",
                "ADST_CEB_FNSTMT_T",
                "ADST_CEB_FNSTMT",
                "ADST_CEB_FNTR",
                "ADST_CEB_FRAUD",
                "ADST_CEB_GRDINTVL",
                "ADST_CEB_HISTORY",
                "ADST_CEB_INTVL",
                "ADST_CEB_ITEMCD",
                "ADST_CEB_KSIC",
                "ADST_CEB_LMTCTL",
                "ADST_CEB_MNGINFO",
                "ADST_CEB_MONITERING",
                "ADST_CEB_NAVL",
                "ADST_CEB_PRJCTRTO",
                "ADST_CEB_REFDTL",
                "ADST_CEB_REFINTVL",
                "ADST_CEB_SHRHLD",
                "ADST_CEB_SLBYER",
                "ADST_CEB_SLDTLS",
                "ADST_CEB_SLINFO",
                "ADST_CEB_SLPCMTHD",
                "ADST_CEB_SLSINFO",
                "ADST_CEB_STDRDZT",
                "ADST_CEB_TRADTR",
                "ADST_CEB_WEIGHT",
                "ACOM_COM_EXRTREL",
                "ADST_CRYP_TRSC_CNTP_BASE",
                "ADST_CUST_DEFL_BASE",
                "ADST_F_CUST_DEFL_BASE",
                "ADST_GRP_SMNS_BWR_BASE",
                "ADST_HL_CORP_RTL_RST_SUMR",
                "ADST_UNFY_AST_CLAS_SUMR",
                "TBCR_MTHRCAGRD",
                "TBCR_MTHRDLQ",
                "TBCR_MTHREWGRD",
                "TBCR_MTHRFIN",
                "TBCR_OTHRCAGRD",
                "ADST_DEFL_JOB_BASE",
                "ADST_DEFL_JOB_HIST",
                "ADST_ACCT_DEFL_BASE",
                "ADST_ACCT_DEFL_HIST",
                "ADST_CUST_DEFL_HIST",
                "ADST_DEFL_EXC_REG_BASE",
                "ACOM_DLY_NPVCKPN",
                "ACOM_OVERDUE_BASE",
                "ACOM_OVERDUE_DTLS",
                "ADST_DPB_BLOCK",
                "ACOM_BAT_AUTOSCH",
                "ACOM_BAT_JOBBASE",
                "ACOM_BAT_JOBINFO",
                "ACOM_BAT_PGMBASE",
                "ACOM_BAT_PROCLST",
                "ADST_CEB_FILE",
                "ADST_WFL_GOVN_BASE",
                "ADST_WFL_GOVN_HIS",
                "ADST_DPB_FLPP_TRAN",
                "ADST_WFL_REQ_MST_FLPP",
                "ADST_WFL_REQ_BASE",
                "ADST_WFL_REQ_SCH_FLPP",
                "ACOM_IFRS_LBUDTLS_FRM",
                "AEBK_EBB_RECON_REF",
                "ACOM_IFRS_ADJCOLGD",
                "ACOM_IFRS_EXTMACRO",
                "ACOM_IFRS_LBUDTLS",
                "ACOM_IFRS_LGD",
                "ACOM_IFRS_MATRIX",
                "ACOM_IFRS_PDINFO",
                "ACOM_IFRS_REGRESSION",
                "ACOM_IFRS_SETTLEDNPL",
                "ACOM_IFRS_UNUSEDFAC",
                "ACOM_DLY_IFRSRATE",
                "ACOM_DLY_NPVCKPNSUM",
                "ACOM_SEQUENCE_BASE",
                "ACOM_COM_SEQ",
                "ACOM_COM_REFNO",
                "ACOM_COMH_MSGSEQ",
                "ACOM_COMH_REFALLOW_IFRS",
                "ACOM_IFRS_DPDS",
                "ACOM_IFRS_LBUDTLS_ORG",
                "ACOM_IFRS_PDBASE",
                "IDEB01_HEADER",
                "ADST_CEB_ESFSALACTCD",
                "ADST_CEB_ESFSALRST",
                "ARDN_ACCT_BASE",
                "ARDN_ACCT_HIS",
                "ARDN_ACCT_ITM",
                "ARDN_BATCH_BASE",
                "ARDN_BATCH_HIS",
                "ARDN_CUST_BASE",
                "ARDN_CUST_HIS",
                "ARDN_CUST_ITM",
                "ARDN_MSG_KSEI_STATIC",
                "ARDN_MSG_KSEI_STMT",
                "ARDN_PE_INFO",
                "ARDN_PE_ITM",
                "ACOM_IFRS_SETTLEDNPL_FRM",
                "ACOM_CIX_BLST",
                "ACOM_ATB_UPLOAD",
                "ACOM_SIS_LOGSEQ",
                "ACOM_TBBS_WLISTFACTIVA",
                "TEMP_BATCHDATA_CERT",
                "AEBK_EOH_RESP",
                "AEBK_EBH_QRIS",
                "AEBK_EBH_AREA_VEND",
                "AEBK_EBH_REQ_BASE",
                "AEBK_EBH_REQ_BASE_HIS",
                "AEBK_EBH_BOOTH_STK",
                "AEBK_EBH_MTRL_STK",
                "AEBK_EBH_DELIVERY",
                "AEBK_EBH_DELIVERY_HIS",
                "AEBK_CSH_B24_AA02_BAK",
                "AEBK_CSH_B24_AA03_BAK",
                "AEBK_CSH_B24_XA01_BAK",
                "AEBK_CSH_B24_XA01I_BAK",
                "AEBK_CSH_B24_XB01S_BAK",
                "AEBK_CSH_B24_XI01S_BAK",
                "AEBK_CSH_IDEA_BRSM",
                "AEBK_CSH_IDEA_BRSM_A",
                "AEBK_CSH_IDEA_BRSM_B",
                "AEBK_CSH_IDEA_BRSM_C",
                "AEBK_CSH_IDEA_BRSM_D",
                "AEBK_CSH_IDEA_BRSM_KLM",
                "AEBK_CSH_IDEA_BRSM_RKP",
                "AEBK_CSH_IDEA_FILE_IODET",
                "AEBK_CSH_IDEA_FILE_MASTER",
                "AEBK_CSH_IDEA_NPG_B_01",
                "AEBK_CSH_IDEA_NPG_B_02",
                "AEBK_CSH_IDEA_NPG_B_03",
                "AEBK_CSH_IDEA_NPG_B_04",
                "AEBK_CSH_IDEA_NPG_B_07",
                "AEBK_CSH_IDEA_VISA_01A",
                "AEBK_CSH_IDEA_VISA_01B",
                "AEBK_CSH_IDEA_VISA_02",
                "AEBK_CSH_IDEA_VISA_04",
                "AEBK_CSH_NPG_D1",
                "TMP_SCAN_CHECK",
                "AEBK_CSH_IDEA_NPG_P_02",
                "AEBK_CSH_IDEA_PRIMA_A",
                "AEBK_CSH_IDEA_PRIMA_BPREV",
                "AEBK_CSH_IDEA_PRIMA_E2",
                "AEBK_CSH_IDEA_PRIMA_F2",
                "AEBK_CSH_B24_XB02_BAK",
                "AEBK_CSH_B24_XB02S_BAK",
                "AEBK_CSH_B24_CA02_BAK",
                "AEBK_CSH_B24_CA03_BAK",
                "AEBK_CSH_B24_CI02_BAK",
                "AEBK_CSH_IDEA_PRIMA_C",
                "AEBK_CSH_IDEA_PRIMA_F1",
                "AEBK_CSH_IDEA_PRIMA_TC",
                "AEBK_CSH_IDEA_PRIMA_B",
                "AEBK_CSH_IDEA_PRIMA_D",
                "AEBK_CSH_IDEA_PRIMA_TD",
                "AEBK_CSH_GL_JURNAL",
                "AEBK_CSH_B24_CHG",
                "AEBK_CSH_B24_SCHG",
                "AEBK_EIH_CVV_HIS",
                "AEBK_CSH_IDEA_PRIMA_E1",
                "AEBK_CSH_IDEA_PRIMA",
                "AEBK_CSH_REFUND_LIST_20191028",
                "AEBK_CSH_REFUND_LIST_191028_1",
                "ACOM_COM_ALERT",
                "AEBK_CSH_FDS_BLK_CARD",
                "AEBK_CSH_FDS_BLK_MCC",
                "AEBK_CSH_FDS_BLK_RLT",
                "AEBK_CSH_FDS_BLK_STOR",
                "AEBK_CSH_FDS_BTCH_CARD",
                "AEBK_CSH_FDS_BTCH_STOR",
                "AEBK_CSH_FDS_BTCH_TERM",
                "AEBK_CSH_FDS_RST_NATN",
                "AEBK_CSH_FDS_RTM_RLT",
                "AEBK_CSH_FDS_RUL_DAT",
                "AEBK_CSH_FDS_RUL_RLT",
                "AEBK_CSH_FDS_RUL_VLU",
                "AEBK_CSH_FDS_SML_RLT",
                "AEBK_CSH_FDS_TRNS",
                "AEBK_CSH_FDS_VLU_MAP",
                "AEBK_CSH_FDS_WHT_LST",
                "TEMP_UNIT_BALANCE_MF",
                "AEBK_CSH_IDEA_PRIMA_C_NPG_SUM",
                "AEBK_CSH_IDEA_PRIMA_C_H_NPG",
                "AEBK_CSH_IDEA_BRSM_B_H_NPG",
                "AEBK_CSH_IDEA_VISA_JURNAL",
                "AEBK_EIH_NAUTH_HIS",
                "AEBK_CSH_B24_XB01_20191127",
                "AEBK_CSH_B24_CA01_20191127",
                "AEBK_CSH_B24_CI01_20191127",
                "AEBK_CSH_GL_JURNAL_20191127",
                "CSS_DEV_KTA",
                "CSS_PEFINDO_MST",
                "CSS_PEFINDO_REQUEST",
                "CSS_PEFINDO_REQUEST_FULL",
                "PBKB_CIP_LIST",
                "PBKB_CIP_REASON",
                "PBKB_CIP_SUMMARY",
                "PBKB_CIQ",
                "PBKB_COLLATERAL_LIST",
                "PBKB_COLLATERAL_SUMMARY",
                "PBKB_COMPANY",
                "PBKB_CONTRACT_COLLATERAL_LIST",
                "PBKB_CONTRACT_DISPUTE_LIST",
                "PBKB_CONTRACT_LIST",
                "PBKB_CONTRACT_OVERVIEW_LIST",
                "PBKB_CONTRACT_PCAL_LIST",
                "PBKB_CONTRACT_REL_SUBJ_LIST",
                "PBKB_CONTRACT_SMRY_PCAL_LIST",
                "PBKB_CONTRACT_SMRY_SINFO_LIST",
                "PBKB_CONTRACT_SUMMARY",
                "PBKB_CURRENT_RELATION_LIST",
                "PBKB_DASHBOARD",
                "PBKB_DISPUTE_LIST",
                "PBKB_DISPUTE_SUMMARY",
                "PBKB_FINANCIAL_LIST",
                "PBKB_INDIVIDUAL",
                "PBKB_INQUIRY_LIST",
                "PBKB_INQUIRY_SUMMARY",
                "PBKB_INVOLVEMENT_LIST",
                "PBKB_INVOLVEMENT_SUMMARY",
                "PBKB_OTHERLIABILITY_LIST",
                "PBKB_OTHERLIABILITY_SUMMARY",
                "PBKB_SECURITY_LIST",
                "PBKB_SECURITY_SUMMARY",
                "PBKB_SUBJECTINFO_HISTORY",
                "PBKO_APPI",
                "PBKO_APPI_OLD",
                "PBKO_BPJSTKPO",
                "PBKO_COURTS",
                "PBKO_DJP",
                "PBKO_MA",
                "PBKO_TASPEN",
                "PEFINDO_KTA",
                "PEFINDO_KTA_REQUEST",
                "AEBK_CSH_GL_JURNAL_20191211",
                "ADST_LNB_NPL_ACR_HIS",
                "ACOM_COM_EPROC",
                "ACOM_IFRS_LEASE_BASE",
                "ACOM_IFRS_LEASE_HIS",
                "ACOM_IFRS_LEASE_BORCOST",
                "ACOM_IFRS_LEASE_CFLW",
                "ACOM_IFRS_LEASE_RENLIAB",
                "ACOM_IFRS_LEASE_RIGHTUSE",
                "ACOM_IFRS_LEASE_BORCOST_REF",
                "ADST_OTHL_BASE_DTLS",
                "ACOM_IFRS_WOAYDA",
                "ACOM_IFRS_LEASE_ETCTRNS",
                "ADST_DPB_BLOCK_PRGM",
                "ADST_WFL_FLPP_BASE",
                "ADST_WFL_FLPP_HIS",
                "AEBK_LBH_BASE",
                "AEBK_LBH_HIS",
                "AEBK_LBH_LIMIT",
                "AEBK_LBH_NOTI_AF",
                "AEBK_LBH_NOTI_BF",
                "AEBK_LBH_TRXHIS",
                "ACOM_CIX_LJOB",
                "ACOM_MSG_ACCT_DTLS",
                "ACOM_MSG_ACCT_THRDPRTY",
                "ADST_LNB_NPWP",
                "TEMP_DATA_DORMANT",
                "ADST_DPB_GIFT_CASH",
                "ADST_DPB_GIFT_CASH_ITM",
                "AEBK_EBH_PRMO_HIT_HIS",
                "AEBK_EBH_PRMO_TRM",
                "AEBK_EBH_QRIS_PRMO_MCH",
                "FBCD_BANCA_DALY_BALS_HST_TEMP",
                "FBCD_BANCA_CONT_BASE_TEMP",
                "GRPGRANT_TMP_EY",
                "TMP_ACOM_COMH_GRPGRANT",
                "TMP_IDC_ACOM_COMH_USER",
                "TMP_SHS_RISK",
                "TEMP_MODIFY_ACCT",
                "TEMP_LOAN_RESTRUCT",
                "AEBK_EBH_REDEEM_ACTIVE",
                "ACOM_NOTIF_BATCH",
                "TMP_CIX_NO",
                "AEBK_CSH_NPG_BRSM",
                "AEBK_CSH_IDEA_FILE_MASTER_BAK",
                "AEBK_EBH_PRMO_TRGT",
                "AEBK_EOH_DUKCALL_LOG",
                "AEBK_CSH_IDEA_PRIMA_GABUNGAN",
                "AEBK_CSH_IDEA_GABUNGAN_SUM",
                "AEBK_CSH_IDEA_PRIMA_SUM",
                "AEBK_CSH_B24_AA01",
                "AEBK_CSH_B24_AA02",
                "AEBK_CSH_B24_AA03",
                "AEBK_CSH_B24_AI01",
                "AEBK_CSH_B24_AI02",
                "AEBK_CSH_B24_CA01",
                "AEBK_CSH_B24_CA02",
                "AEBK_CSH_B24_CA03",
                "AEBK_CSH_B24_CI01",
                "AEBK_CSH_B24_CI02",
                "AEBK_CSH_B24_XA01",
                "AEBK_CSH_B24_XA01I",
                "AEBK_CSH_B24_XA02",
                "AEBK_CSH_B24_XA02I",
                "AEBK_CSH_B24_XA03",
                "AEBK_CSH_B24_XA03I",
                "AEBK_CSH_B24_XB01",
                "AEBK_CSH_B24_XB01S",
                "AEBK_CSH_B24_XB02",
                "AEBK_CSH_B24_XB02S",
                "AEBK_CSH_B24_XI01",
                "AEBK_CSH_B24_XI01S",
                "AEBK_CSH_B24_XI02",
                "AEBK_CSH_B24_XI02S",
                "AEBK_CSH_BRSM_NPG_RAW",
                "AEBK_CSH_BRSM_RKP_RAW",
                "AEBK_CSH_BRSM_TRX_RAW",
                "AEBK_CSH_BRSM_KLM_RAW",
                "AEBK_CSH_PRMA_NPG_RAW",
                "AEBK_CSH_PRMA_NPG_DSPT",
                "AEBK_CSH_P_B_HOBIS",
                "AEBK_CSH_HOBIS_VALID",
                "AEBK_CSH_RAW_FILE_CONFIG",
                "AEBK_CSH_GL_JURNAL_20200710",
                "AEBK_CSH_B24_ST",
                "AEBK_CSH_FDS_SMS_MAIL",
                "AEBK_CSH_BRSM_ST",
                "ACOM_WCH_HIS",
                "ACOM_WCH_BASE",
                "TEMP_DEPOSIT_RESTRUCT",
                "AEBK_CSH_REFUND_LIST_20200730",
                "AEBK_CSH_REFUND_LIST",
                "TMP_JOURNAL_TRK",
                "AEBK_CSH_IDEA_VISA_EP705",
                "AEBK_CSH_IDEA_VISA_EP745",
                "TEMP_DATA_CIFI1",
                "TEMP_BACTHDATA_CIFTRANSFER",
                "TEMP_BACTH_CIFBULK",
                "ACOM_CIX_IDX",
                "DATA_AGUSTUS_501",
                "AEBK_DSH_TOKEN_HIS",
                "AEBK_EIH_API_HIS",
                "ACOM_CIX_FXTR",
                "AEBK_EBH_OLBD_PRMO",
                "AEBK_EBH_BLPC_PRMO",
                "AEBK_ECH_STOPPER",
                "ACOM_CIX_FDS",
                "AEBK_LBH_PTCL",
                "AEBK_EBH_PRMO_DTLS",
                "TEMP_FOR_TEST",
                "ACOM_COMH_DKCP",
                "ACOM_COMH_DKCP_DTLS",
                "TMP_CEK_ACR",
                "TMP_INS_ACR",
                "TEMP_DATA_CIFI",
                "TMP_CHK_MAPPING",
                "ADST_LNB_TRXHIS",
                "ADST_LNB_INSTALL_INFO",
                "ADST_LNB_CONT_ITM",
                "ADST_LNB_BILL_BASE",
                "TEMP_DATA_HANAEMPLOYEE1",
                "TEMP_DATA_HANAEMPLOYEE",
                "TEMP_BATCH_TERMIDEMP",
                "TEMP_TERMID_CIFACCT",
                "TEMP_BATCH_TERMIDEMP_CIFACCT",
                "ADST_OTHL_DAILY",
                "ACOM_COM_SKIPREF",
                "ACOM_COMH_MANAGERHIS",
                "TEMP_DATA_SID",
                "TEMP_SID",
                "TEMP_INS_KEL_HBS",
                "AEBK_EOH_SMS_MQ",
                "AEBK_EOH_HIS_MQ",
                "ACOM_OVERDUE_PTCL",
                "AEBK_EBH_QRIS_ATM",
                "TEMP_BATCH_CHB0200",
                "ACOM_COMH_DKCP_OVRD",
                "TEMP_INS_KEC_HBS",
                "TEMP_INS_KEC_MAP",
                "ACOM_NOTIF_EMAIL",
                "TEMP_CIX_DOUBLE",
                "ACOM_COM_CARD",
                "TEMP_UPD_DESC",
                "ACOM_BATCH_PGMBASE",
                "ACOM_BATCH_PGMHIS",
                "ACOM_BATCH_PROCLST",
                "ACOM_BATCH_JOBBASE",
                "ACOM_BATCH_JOBHIS",
                "ACOM_BATCH_JOBREL",
                "ACOM_NOTIF_EMAILTMPL",
                "ADST_OTHL_PROCCHK",
                "ACOM_CIX_LSEQ",
                "SHC_COL_ERROR_LIST",
                "SHC_COL_VALUE_TEMP",
                "SHC_COL_VALUE_VALID",
                "ADST_LNB_CSS_RESULT",
                "TEMP_LBU_CLEANSING",
                "ADST_LNB_SET_CYCLE",
                "ADST_LNB_INTRT",
                "AEBK_PROD_BASE_RENEW",
                "TEMP_CIF_DOWNGRADE",
                "ACOM_BATCH_DATA_BULK",
                "TEMP_CIF_STORE",
                "TEMP_LINE_TRX_20210905",
                "TEMP_ADST_LINE_TRAN_20210905",
                "TEMP_ADST_LINE_TRAN2",
                "TEMP_SINVEST_FILE",
                "TEMP_CEK_RISKSHS",
                "TEMP_DATA_ACCT",
                "TEMP_AEBK_EIH_MAP",
                "ACOM_SIS_BASE1",
                "ACOM_SIS_BASE",
                "SYS_EXPORT_SCHEMA_01",
                "GAIAB_IMG_LOG_PTCL_X",
                "SYS_IMPORT_TABLE_01",
                "IDEBTB11_HEADER",
                "IDEBTB51_FILEPROFILE",
                "TUNE_INDEX_DESIGN",
                "PLAN_TABLE",
                "PBKB_REPORTMAIN",
                "PBKO_REPORTMAIN",
                "HT_AEBK_ECH_BASE",
                "ADST_DPB_TAXINFO",
                "AEBK_ECH_BAT_TR_VA_BASE",
                "AEBK_ECH_BAT_TR_VA_PTCL",
                "ADST_RSK_QUESTIONER_TRX",
                "ADST_RSK_QUESTIONER_TRX_HIS",
                "ADST_RSK_QUESTIONER_TRX_ITM",
                "ADST_RSK_QUESTIONER_TRX_ITM_HIS",
                "ADST_RSK_QUESTIONER_TRX_APPRV",
                "FBCD_BANCA_POI",
                "TOAD_PLAN_TABLE",
                "ADST_LNB_INTRT_MTRX",
                "AEBK_CSH_BLOCK_RELEASE",
                "ACOM_COMH_CLSLOG",
                "AEBK_CNH_NOTI_BF",
                "AEBK_CNH_NOTI_AF",
                "ACOM_SVC_EXT",
                "ACOM_LEDG_COM_CD",
                "ACOM_SCRN_COM_CD",
                "AACT_ACTG_EVNT_BASE",
                "ACOM_LOG_MGNT",
                "AFTR_FFH_BASE",
                "AFTR_FFH_INFO",
                "AFTR_FFH_PL",
                "AFTR_FFH_REL",
                "AFTR_PFH_EXT",
                "AFTR_PFH_INFO",
                "AFTR_PFH_REL",
                "AFTR_INT_INFO",
                "AFTR_INT_PL",
                "ALDM_DPB_IRRT",
                "AEBK_EBB_RECONHIS",
                "AEBK_CSH_FDS_SMS_MAIL_HIS",
                "AEBK_EBH_INFO",
                "ACOM_TBBS_WLIST_TRXBLK",
                "ACOM_LBH_BULK_PYRL_PTCL",
                "ACOM_LBH_BULK_PYRL_BASE",
                "AEBK_BLLPAY_HIS",
                "FBCD_BOND_PROD_POI",
                "AEBK_EBH_HIS_INFO",
                "AEBK_EBH_LMT_MST",
                "AEBK_EBH_LMT_RGST",
                "AEBK_EBH_LMT_TRX",
                "AEBK_EBH_PRMO_CODE",
                "FBCD_BANCA_DALY_BALS_HST_VAL",
                "FBCD_BANCA_CONT_BASE_VAL",
                "FBCD_BANCA_FUND_IVT_INFO_VAL",
                "FBCD_BANCA_RIDER_INFO_VAL",
                "ADST_LNB_BAT_NOTIFY",
                "ADST_LNB_CONT_BASE",
                "AFBK_FKH_BAT_BILL_PTCL",
                "ADST_LNB_PORTFOLIO_SUB",
                "ADST_LNB_PORTCUST_CHK",
                "ADST_LNB_PORTCUST",
                "ADST_LNB_PORTFOLIO",
                "MRTP_RE62_CM024",
                "AEBK_LBH_CARD_FEE_BASE",
                "AEBK_LBH_CARD_FEE_PRMO",
                "AFEX_XPB_INFO",
                "ACOM_TBBS_WLISTCREDIT",
                "ADST_DPB_CHNG_PROD",
                "MRTP_RE62_LN010",
                "MRTP_RE62_LN002",
                "MRTP_RE62_LN009",
                "MRTP_RE62_LN011",
                "MRTP_RE62_LN012",
                "AEBK_EBB_RECONLOG_BF",
                "AEBK_EBB_RECONLOG_AF",
                "AEBK_BFH_RECON_CREDIT",
                "TEMP_COMH_FRECOG",
                "AEBK_BFH_RECON_REFUND",
                "TEMP_NEW_NOTIF_SMS",
                "ACOM_NOTIF_SMS",
                "ACOM_POA_BASE",
                "AEBK_EOH_NOTI_EVNT",
                "AEBK_EOH_NOTI_BF",
                "AEBK_EOH_NOTI_AF",
                "DEPT_JSON_BODY_VAR",
                "DEPT_JSON_HEADER_TMP",
                "DEPT_JSON_HEADER_VAR",
                "ACOM_TBBS_LINEONBOARD",
                "ADST_LNB_TENOR_MTRX",
                "ADST_SDB_PRICING",
                "TEMP_DM_APPRAISAL",
                "FBCD_AID_MP_BASE_LOAD",
                "FBCD_AID_MP_ITM_PTCL_LOAD",
                "FBCD_AID_ROBO_MP_BASE",
                "FBCD_AID_ROBO_MP_ITM_PTCL",
                "AFTR_INT_BASE",
                "AEBK_EBB_CM612",
                "AEBK_EBH_BLOCK",
                "AEBK_BFH_SUSP",
                "AEBK_BFH_SUSPHIS",
                "ACOM_COM_ATTRNY_TEMP",
                "ACOM_COM_ATTRNY_TRX",
                "AEBK_BOH_LMT_BASE",
                "AEBK_BOH_LMT_DTLS",
                "AEBK_BOH_LMT_TRX",
                "ACOM_DMB_CRSCLT",
                "ACOM_POI_BASE",
                "ACOM_COMH_SDB_BASE",
                "ACOM_COMH_SDB_HIS",
                "ACOM_COMH_SDB_PRICING",
                "AEBK_CSH_FDS_BLK_ACC",
                "DEPT_JSON_BODY",
                "AEBK_CSH_BRSM_KLM_RAW_BAK",
                "AEBK_CSH_BRSM_TRX_RAW_BAK",
                "AEBK_BOH_HIS",
                "AEBK_CSH_FDS_TEMP",
                "ADST_RSK_QUESTIONER_TRX_ITMHIS",
                "AEBK_EBH_TRM_DTLS",
                "ADST_LNB_PORTCUST_HIS",
                "ZTEMP_AEBK_CSH_P_B_HOBIS",
                "AEBK_BFH_RECON_DTLS",
                "AEBK_EBH_PRMO_REF",
                "ACOM_CIX_REFID",
                "MRTP_RE62_CM322_MIRROR",
                "AEBK_EBH_ATMRECEIPT",
                "temp_kilun_dua",
                "IDEBVW20_DEBTORS",
                "IDEBVW30_ACCOUNTS",
                "AACT_ACR_HIS",
                "AACT_ACT_EVNT_TRSC",
                "AACT_TEL_HIS",
                "AACT_TRX_ACTLOG_AF",
                "AACT_TRX_ACTLOG_NEWAF",
                "AACT_TRX_BAL",
                "AACT_TRX_BASE",
                "AACT_TRX_BS",
                "AACT_TRX_PL",
                "ACOM_DMB_AQC",
                "ACOM_REH_REPCUST",
                "ACOM_REH_REPORT",
                "ACOM_SIS_LOG",
                "ADST_DPB_HIS",
                "ADST_DPB_TRAN",
                "AEBK_EBH_HIS",
                "AEBK_EIH_HIS",
                "AEBK_EOH_HIS",
                "AEBK_EOH_SESS",
                "AFTR_FFH_COMM_TRSC_PTCL",
                "MRTP_RE62_CM322",
                "TBCR_EWCANO"};

        return tableList;
    }


    private static String[] getBizList() {

        String[] bizList = {
                "ad",
                "ai",
                "at",
                "bc",
                "bd",
                "bl",
                "bt",
                "ca",
                "ce",
                "cg",
                "ch",
                "ck",
                "cl",
                "cm",
                "co",
                "cs",
                "cx",
                "dm",
                "dp",
                "dt",
                "en",
                "ep",
                "ew",
                "fa",
                "fb",
                "fe",
                "ff",
                "fk",
                "fn",
                "fs",
                "ft",
                "gt",
                "hf",
                "if",
                "im",
                "ip",
                "iq",
                "ll",
                "ln",
                "lr",
                "ma",
                "mm",
                "mt",
                "ob",
                "ot",
                "pf",
                "ra",
                "rc",
                "rd",
                "re",
                "rk",
                "rt",
                "sd",
                "tk",
                "tr",
                "ts",
                "wf",
                "wm",
                "xp"
        };

        return bizList;
    }
}
